### ISSUE TITLE
OAuth2 URL

### ISSUE THREAD

**Issue by jmawebtech** [EventDay/Infusionsoft.net#37]
Hi,

I am using Infusionsoft's OAuth2. In the current release, you are pointing to the old URL:

Infusionsoft/InfusionsoftProxy

private const string UriMask = "https://{0}.infusionsoft.com/api/xmlrpc";

Can you make a property that allows me to change the UriMask, if the user runs OAuth2? I have several clients running on the API keys and I do not wish to disrupt their sync.

In my code, I would like this:

         public InfusionSoftProvider(string application, string apiKey, bool oAuth2)
        {
            if (String.IsNullOrEmpty(apiKey))
                return;

            this.application = application;
            this.apiKey = apiKey;
            var customer = new Customer(application, apiKey);
            client = customer.Connect();

            if(oAuth2)
                client.UriMask = "https://api.infusionsoft.com/crm/xmlrpc/v1?access_token=TOKEN"
            
            client.MethodListener = new ConsoleMethodListener();
            ispMapper = new ISPMapper(client);
        }

**Comment by trbngr** [comment]
Can you please issue a pull request?

**Comment by jmawebtech** [comment]
Hi Chris,


Thanks for the follow up.


I went to the home screen and I clicked pull requests. I see a screen saying that are no pull requests. I click create a new pull request, but I can find no branch to compare. What am I doing incorrectly?



Joseph Anderson

Director, Customer Success

JMA Web Technologies, Inc.

P: (781) 330-0737

Web: http://www.jmawebtechnologies.com

Store: http://www.jmawebstore.com


________________________________

**Comment by scottcate** [comment]
Hi Joseph, A pull request is a way of submitting code that you customize into the repo. You would bring the code local, make your changes, add features, whatever. Then once you want to submit those code changes you would ask the repo owners (us in this case) to "Pull" your changes. Hence the name, "Pull Request"

More Info: https://help.github.com/articles/using-pull-requests/

**Comment by jmawebtech** [comment]
Hi Scott,

I am unsure what code to add and in what files to make your library compatible with the OAuth API. It appears difficult to change the posting URL, based on your architecture. Can you add a public property on the customer object?

**Comment by jmawebtech** [comment]
I think that I checked it in, but I cannot find it. Please see if it is there.


Joseph Anderson

Director, Customer Success

JMA Web Technologies, Inc.

P: (781) 330-0737

Web: http://www.jmawebtechnologies.com

Store: http://www.jmawebstore.com


________________________________

**Comment by scottcate** [comment]
Hi Joseph, Currently the project does not support oAuth. This is a much bigger feature request than just changing a URL. At this time, we're still relying on XMLRPC an doAuth is not available.

As this open source project is maintained by the community, we would invite you to invest in this feature and once working, issue a pull request to the project.
