### ISSUE TITLE
DataService.Count

### ISSUE THREAD

**Issue by UserSud** [EventDay/Infusionsoft.net#41]
Hi 
I can't seem to find it but can someone point me to where I can tap into the Count methods please?
I see it in https://developer.infusionsoft.com/docs/xml-rpc/#data-count-a-data-table-s-records
But can't seem to find it here

Hope you can help

Many thanks!

**Comment by hfloyd** [comment]
Hi @UserSud, 
I also noticed the lack of the Count Methods. I'm not sure how this will work with large datasets, but I was able to get around it with code like this:

`var recordsCount = _connectionClient.DataService.Query<TABLENAME>().Count(); `

ex: 
`var tagsCount = _connectionClient.DataService.Query<ContactGroup>().Count(); `

**Comment by UserSud** [comment]
Hi @hfloyd 
Thanks for this.
It works!  But you're right depending on the size of the table it could take a while. 
I wonder if it's pulling the whole table over before giving the count :-(

Thanks for the code sample.

**Comment by hfloyd** [comment]
Glad to help, @UserSud :-)
